# Ego’s Network

We will go through the process of designing and conducting a social network study. 

## Finding a research topic

A research topic can be considered good if interesting, relevant, has not been answered or researched before or is measurable. 

<aside>
❓ *For instance, we could focus on people who live abroad.*

</aside>

## Identify a research question

<aside>
❓ Related to people who live abroad, some research questions could be *How do people experience moving home and why? what factors make it good or bad for them? How do Hungarian returning migrants experience their return and what are the
main factors that affect their experiences?*

</aside>

## Think about relevant theories

Is there a theory that directly adresses or answers our question?

<aside>
❓ *Are there any sociological theories or concepts that help us think about why some people are happier in general or cope better in certain situations? Maybe something you learnt in class?*

</aside>

### Coleman - Closure

Let’s consider the social capital theories. James Coleman in 1988 focuses on the function of social capital, which according to the economic sociology is based on a rational choice approach: it attempts to introduce social structure into his analysis by employing social capital and social norms to explain how individual rational actions translate into systematic collective action.

It is not a single entity, but a variety of entities, having two characteristics in common: they all consist of some aspect of social structure, and they facilitate certain actions of individuals who are within the structure. There are three forms of social capital: obligations and expectations; information channels; social norms. 

A key concept is about **closure or bonding capital**, which facilitates obligations and expectations and social norms and takes the form of trust, social norms of reciprocity and cooperation. 

### Burt and Granovetter - Bridging

According to Burt and Granovetter, Social capital is is a resource that is embedded in social networks and is accessible to individuals through their social connections. Information is the key resource in social networks.

People with strong ties come from the same social circle thus have access to the same information. However, weakly related ties are members of other social groups and have access to different, non-redundant information. The key concept is bridging or the presence of weak ties.

### Nan Lin

According to Nan Lin, social capital can be defined as resources embedded in a social structure which are accessed and/or mobilised in purposive action.

It cuts through the debate of bridging vs closure: differentiates two different kinds of returns to social capital, that result from different mechanisms:

- Instrumental returns to social capital, which arises from bridging capital and enables individuals to access resources they previous did not have (e.g. money, wealth, reputation, power);
- Expressive returns to social capital, which arises from bonding capital (closure) and enables individuals to preserve previously existing resources (e.g. physical health, mental health, life satisfaction).

### Social Support

Social Support is closely related to Social Capital, being an inherently relationship-based concept. It highlights the assistive nature of personal relationships. It can be defined as people are surrounded by a variety of social ties, which provide them with different supportive resources.

Different forms of social support (to capture the diversity) are:

- Emotional support: someone you can talk to when you have a problem;
- Instrumental or practical support: someone can help you with your groceries when you brake your leg. Can also include information;
- Financial support: someone can lend you some money when you are bankrupt;
- Social companion: someone you can spend your free-time with, for example grab a beer with after class.

## Data collection

There are two major kinds of network research designs:

- **Socio-centric or whole network design**
    
    It starts with a set of all the actors. Then we collect all the connection between all the actors. We get a single and complete network. 
    
    It captures the position of individuals within the social structure. It can measure indirect or absent ties.
    
- **Ego-centric or personal network design**
    
    It starts with a sample of actors from a population. Each of them provides information about the members of their own network. We get a set of separate networks. 
    
    It also captures the position of individuals within the social structure but its limited to direct ties. 
    

## From theory to practice

- **Socio centric**
    
    **Requirements**: 
    
    It requires the identification of a boundary inside a population. It’s important for individuals’ position within the network. As a result, it is focused on a social domain. It requires the collection of all ties of all nodes within the population to every other node within the population. 
    
    **Privacy**: 
    
    There are however ethical concerns due to the lack of anonymity, otherwise it is not possible to construct the whole network. 
    
    **External validity**:
    
    We cannot generalize our assumptions for all networks, but just for the whole one we’re studying, since each one of them may have different dynamics. 
    
    <aside>
    ❓ *Let’s say we make a network study of your network class here and conclude that the tallest person has the most central position. Does it hold for your other classes too? And for other universities? Also for undergraduate students? For other network classes at other universities? Since we didn’t sample students from all Italian (or European) universities, we cannot generalise*
    
    </aside>
    
- **Ego centric**
    
    **Requirements**: 
    
    Each person lives in a personal community that’s unique to them (i.e. social context). This social context affects individuals in multiple ways. We want to collect data from the individual’s (ego) perspective to understand their social context. 
    
    We don’t have to artifically define the boundaries of the network – not restricted to a group. It can also span multiple social domains. It’s typically easier to collect these data instead of the whole network. Each person nominated by default has a connection to the interviewed individual. Connection between nominated individuals may or may not be collected. 
    
    **Privacy**: 
    
    Respondents’ identity can be kept anonymous and also the nominated people (they can use pseudonyms).
    
    **External validity:**
    
    When egos are randomly selected from a wider population we may be able to generalise our findings.
    
    <aside>
    ❓ *For instance, a random selection of MA students from all italian universities are interviewed about their friends both within and outside their university.*
    
    </aside>
    

## Select the right network approach

In order to choose between the socio or the ego-centric approach we must consider 2 main criteria:

- which one suits better for assessing our theoretical approach or answering our research question?
- practical considerations involved in data collection.

### Ego-centric network

The ego-centric network, also called ego-networks, is a network where the person whose network is collected is called ego. The person who are nominated by the ego are called alters. 

In order to collect data for ego-networks:

1. Name generator: who are the members of the network? who are the ego alters? Remember to set a time frame and to limit the size of the network;
2. Name interrelator: how do we define who knows whom in the network? is it weighted or not?
3. Name interpreter: what alter attributes are relevant?

### Generating names of ego-networks

1. Exchange based name generators: elicit ties to provide access to particular resources;
2. Content based name generators: interaction between partners with particular attributes, roles or shared experience;
3. Affect based name generators: elicit intimate alters that are mostly influential;
4. Interaction based name generators: measure the sociability or social isolation.

### How to collect data?

- Questionnaires
- Interviews
- Participant-aided sociograms;
- Target method.