# Two-mode projections

```{r}
######################
# TWO-MODE PROJECTIONS
######################
library(sna)

# Importing data
DSAm <- as.matrix(read.csv(
    "datasets/Davis_SouthernWomen_Attendance.csv",
    stringsAsFactors = FALSE, row.names=1))


# Limit letters to the first two letters
DSAmS<-DSAm
#Change names in new object
rownames(DSAmS)<-substring(rownames(DSAm),1,2)

par(mar = c(0,0,0,0))
# Now draw the network
gplot(DSAmS, displaylabels=TRUE, 
      usearrows=FALSE, gmode="twomode")
```


```{r}
###########################
# ONE MODE PROJECTIONS
###########################

DSAmS%*%t(DSAmS)
t(DSAmS)%*%DSAmS
mean(DSAmS)
```


```{r}
# Example dataset
scientists_papers<-matrix(c(1,0,0,0,0,0,0,0,
                            1,0,0,1,0,0,0,0,
                            1,1,0,0,0,0,0,0,
                            1,1,1,0,0,0,0,0,
                            0,0,1,1,1,1,1,1,
                            0,0,0,0,0,0,1,1),
                          6,8,byrow=TRUE)
rownames(scientists_papers)<-c("a1","a2","a3","a4","a5","a6")
colnames(scientists_papers)<-c("e1","e2","e3","e4","e5","e6","e7","e8")
gplot(scientists_papers, displaylabels=TRUE, usearrows=FALSE, gmode="twomode")
rowSums(scientists_papers)
colSums(scientists_papers)
```


```{r}
#Example of valued network
MATRIX2V<-matrix(c(5,1,0,0,
                   0,3,0,1,
                   0,0,1,3,
                   0,0,0,5,
                   1,5,1,0,
                   0,0,7,4),6,4, byrow=TRUE)
rownames(MATRIX2V)<-c("a","b","c","d","e","f")
colnames(MATRIX2V)<-c("w","x","y","z")
gplot(MATRIX2V, displaylabels=TRUE, 
      usearrows=FALSE, gmode="twomode")
```


```{r}
gplot(MATRIX2V, displaylabels=TRUE, 
      usearrows=FALSE, gmode="twomode",edge.lwd=1)
```

```{r}
# Centrality Measures about Authors
rowSums(scientists_papers)
rowSums(scientists_papers)/NCOL(scientists_papers)
```


```{r}
# Centrality Measures about Papers
colSums(scientists_papers)
colSums(scientists_papers)/NROW(scientists_papers)
```


```{r}
# Proportion of participation of authors for each paper
t(scientists_papers)/colSums(scientists_papers)

# Same but transposed
t(t(scientists_papers)/colSums(scientists_papers))

# Percentage of participation into papers
rowSums(t(t(scientists_papers)/colSums(scientists_papers)))
```


