# Dyads and triads

## Dyads

```{r}
##############################
# DYAD
##############################
mat6<-matrix(c(0,0,0,1,0,0,
               0,0,1,0,0,0,
               0,1,0,0,0,0,
               1,1,1,0,1,1,
               0,0,1,1,0,1,
               0,0,0,0,1,0),6,6, byrow=T)

# Dyad Census
sna::dyad.census(mat6, g=NULL)
```


```{r}
# Like edgewise but multiplied for m/(m+a)
sna::grecip(mat6,measure="dyadic")
```

```{r}
# Edgewise (like we have seen before)
sna::grecip(mat6,measure="edgewise")
```


```{r}
# Density
sna::gden(mat6)
```


```{r}
# With igraph
library(igraph)
mat6i<-graph_from_adjacency_matrix(mat6,mode=c("directed"),diag=F)
igraph::reciprocity(mat6i)
```


```{r}
igraph::edge_density(mat6i)
```

# Triads

```{r}
##############################
# TRIAD
##############################
mat6<-matrix(c(0,0,0,1,0,0,
               0,0,1,0,0,0,
               0,1,0,0,0,0,
               1,1,1,0,1,1,
               0,0,1,1,0,1,
               0,0,0,0,1,0),6,6, byrow=T)

# Triad census
sna::triad.census(mat6)
```


```{r}
sna::gtrans(mat6)
```


```{r}
sna::gden(mat6)
```


```{r}
# Check if it's random
RG100<-sna::rgraph(20,100,tprob=.2)
hist(sna::gden(RG100))
hist(sna::gtrans(RG100))
```